Staff: show spam info
readthedocs/ext-theme pull request #362
Opened 2024-06-05 13:41 UTC by humitos

Allow us to quickly know the spam score of the project and what are their matching rules.

![Screenshot_2024-06-05_15-40-34](https://github.com/readthedocs/ext-theme/assets/244656/051b77f1-df31-4c63-a9df-500aa9739ab0)

2024-06-05 17:30 UTC, agjohnson commented
This is a great addition, however I would add this into a modal instead. I prefer to always see what the user sees in our UI.

I would follow one of the other templates that invokes a modal and copy the pattern to a button here:
![image](https://github.com/readthedocs/ext-theme/assets/1140183/075a6788-e007-4fe8-8d9b-8a8cdd092bd2)

There is other information I'd love to have in that modal eventually, and this amount of information will overwhelm the header.

2024-06-05 17:37 UTC, agjohnson requested changes
The changes look great and I really like this addition, but I would keep site admin content separate from user content, so that there is only a single UI experience. It should be easy to move this into a list in a model though.

2024-06-06 16:30 UTC, humitos commented
Cool, I followed your suggestion and added a modal for this. It gives a lot of room to add more useful debug information here in the future.

![Screenshot_2024-06-06_18-28-20](https://github.com/readthedocs/ext-theme/assets/244656/eea87faf-a649-4998-93b9-518cbcded04c)

2024-06-06 16:32 UTC, humitos commented on readthedocsext/theme/templates/projects/partials/header.html
> +                     {% endif %}
This stopped working once I moved inside a modal. Do you know why?

2024-06-06 18:42 UTC, agjohnson commented on readthedocsext/theme/templates/projects/partials/header.html
> +                     {% endif %}
I'm guessing this is likely because `modal()` is called on the parent element. FUI has some limitations/quirks around floating elements inside floating elements as well, though my guess is JS.

There is also a JS free option for popups/tooltips described in the FUI popup module documentation, which I believe is just CSS. You can try that or using `data-bind="semanticui: { popup: {...}}"`. The implicit, global rules for popups might just not work in modals.

2024-06-06 18:43 UTC, agjohnson commented
That looks great! I really like the idea of having a debug menu for projects (and other objects too!)

2024-06-06 19:03 UTC, humitos commented on readthedocsext/theme/templates/projects/partials/header.html
> +                     {% endif %}
I'll quickly try that, but I'm not too worried if it doesn't work. We can investigate more on this later

2024-06-06 19:15 UTC, agjohnson commented on readthedocsext/theme/templates/projects/partials/header.html
> +        {% if not ALLOW_PRIVATE_REPOS %}
I don't believe `ALLOW_PRIVATE_REPOS` is included in the context at all, and if it is, it is on a per-view basis.

I always use `USE_ORGANIZATIONS` for this reason. It is exported at a global level, in `readthedocs_context()`. We should really have a more specific global context variable here -- `IS_COMMUNITY`/etc -- but for now `USE_ORGANIZATIONS` is closer, global, and by the time organizations are used on community, we should hopefully have finally added a `IS_COMMUNITY` variable :laughing:

2024-06-06 19:15 UTC, agjohnson commented on readthedocsext/theme/templates/projects/partials/header.html
> +          <h3>Spam</h3>
Not super important, but for consistency with below:

```suggestion
          <h3>{% trans "Spam" %}</h3>
```

2024-06-06 19:15 UTC, agjohnson commented on readthedocsext/theme/templates/projects/partials/header.html
> +                  <a href="https://admin.ops.{{ PRODUCTION_DOMAIN }}:10000/admin/spamfighting/spamrule/{{ rule.pk }}/change/"
We should not be exposing this URL in our public repos. It should be a configuration variable.

2024-06-10 11:04 UTC, humitos commented on readthedocsext/theme/templates/projects/partials/header.html
> +                  <a href="https://admin.ops.{{ PRODUCTION_DOMAIN }}:10000/admin/spamfighting/spamrule/{{ rule.pk }}/change/"
We already have this. It's called `ADMIN_URL` 👍🏼

2024-06-10 11:16 UTC, humitos commented on readthedocsext/theme/templates/projects/partials/header.html
> +                     {% endif %}
I tried this but I wasn't able to make it work. We can come back later to this, it was just a "nice to have".

2024-06-10 11:17 UTC, humitos commented
This PR is ready to merge 👍🏼

2024-06-10 15:43 UTC, agjohnson approved these changes

2024-06-10 16:06 UTC, merged