Add project: highlight yaml examples
readthedocs/ext-theme pull request #369
Opened 2024-06-06 12:08 UTC by humitos

I used `highlight.js` to highlight the examples when importing a project. It requires importing a CSS file that I'm not sure where to put it yet.

https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/dark.min.css

Besides, I need to know where to place the small chunk of JS code that I added to make this work.

![Screenshot_2024-06-06_14-02-30](https://github.com/readthedocs/ext-theme/assets/244656/e3bc804f-6b6d-4318-84ee-3a40c9c4a019)

@agjohnson I would appreciate some directions here to clean up and finish this work.

Based on #368

2024-06-06 15:03 UTC, humitos commented
I moved the code where I think it belongs. The only missing piece here is understanding how to include my CSS stylesheet file. Other than that, it seems that everything works as expected 👍🏼

2024-06-06 15:09 UTC, humitos commented
Boom! I figured it out!

2024-06-06 15:17 UTC, humitos commented on readthedocsext/theme/templates/projects/import_config.html
> +          <code  id="project-create-sample-sphinx" class="language-yaml highlight">
`highlight.js` requires this to be `pre > code` and not the other way around 🤷🏼

2024-06-06 20:49 UTC, agjohnson commented
We are already using Pygments on the server side in other places. We should very likely continue with that pattern, I don't feel we should have two ways of highlighting.

You can see the integration HTTP exchange UI, templates, and views for examples of this. I'm guessing it will plug in easily here as well.

2024-06-06 21:54 UTC, agjohnson commented
Noted on the original issue too, the plan when this UI was first added was to come back and switch the examples with tabbed menus and use Pygments for highlighting:

- https://github.com/readthedocs/ext-theme/issues/184

2024-06-06 21:56 UTC, agjohnson requested changes
Probably should have noted my feedback in review here. I think Pygments is the better option here, it doesn't need anything horribly new and will match where we've used Pygments in other UIs.

2024-06-10 12:00 UTC, humitos commented
OK. The original issue said that either worked: pygments or a front-end solution. I will come back to this once I have some extra time and check the pygments solution. However, I will de-prioritize this work for now.

2024-06-10 16:50 UTC, agjohnson commented
Adding a front end dependency works if pygments doesn't work for some reason, but it helps to keep patterns the same and dependencies minimal on the front end side if we can.

2025-07-03 14:46 UTC, closed without merging